//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalElectionTr
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilceler
    {
        public ilceler()
        {
            this.user = new HashSet<user>();
        }
    
        public int ilce_no { get; set; }
        public string ilce_isim { get; set; }
        public int il_no { get; set; }
        public Nullable<int> ilce_akp_oy { get; set; }
        public Nullable<int> ilce_chp_oy { get; set; }
        public Nullable<int> ilce_mhp_oy { get; set; }
        public Nullable<int> ilce_iyi_oy { get; set; }
        public Nullable<int> ilce_saadet_oy { get; set; }
        public Nullable<int> ilce_other { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual iller iller { get; set; }
        public virtual ICollection<user> user { get; set; }
    }
}
