//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalElectionTr
{
    using System;
    using System.Collections.Generic;
    
    public partial class iller
    {
        public iller()
        {
            this.ilceler = new HashSet<ilceler>();
            this.user = new HashSet<user>();
        }
    
        public int il_no { get; set; }
        public string il_isim { get; set; }
        public Nullable<int> il_akp_oy { get; set; }
        public Nullable<int> il_chp_oy { get; set; }
        public Nullable<int> il_mhp_oy { get; set; }
        public Nullable<int> il_ip_oy { get; set; }
        public Nullable<int> il_saadet_oy { get; set; }
        public Nullable<int> il_other { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ICollection<ilceler> ilceler { get; set; }
        public virtual ICollection<user> user { get; set; }
    }
}
